M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sat 30 Aug 2025 12:58:09 AM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-30T00:58:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.1339Y-2.1654
X4.1339Y-5.7087
X7.6772Y-2.1654
X7.6772Y-5.7087
M30
